// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package users

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteAddress(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAddressesByUserID(ctx context.Context, userID sql.NullInt64) (Address, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	InsertAddress(ctx context.Context, arg InsertAddressParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
